use customer_shopping

select * from customer;

show tables;
describe customer;

-- Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, ROUND(AVG(review_rating),2) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select Shipping_type, ROUND(AVG(purchase_amount),2)
from customer
where Shipping_type in ('Standard','Express')
group by Shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q7. What is the revenue contribution of each age group? 

select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;





